import { PDFDocument, PDFImage, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import type { PdfEvidencePhotoInput } from "./pdfEvidence.js";

const PAGE_W = 612;
const PAGE_H = 792;
const MARGIN = 50;
const FOOTER_RESERVE = 52;
const LINE = 14;
const BODY = 11;
const TITLE = 22;
const SUBTITLE = 16;
const HEAD = 12;
const META = 9;
const PHOTO_COLS = 2;
const PHOTO_GAP = 12;
const PHOTO_CELL_H = 200;
const PHOTO_CAPTION_H = 36;

/** Max prefix of `s` (from start) that fits at `size` within `maxW`; at least one code unit if `s` is non-empty. */
function longestFittingPrefix(
  font: { widthOfTextAtSize: (t: string, s: number) => number },
  s: string,
  size: number,
  maxW: number
): string {
  if (!s) return "";
  if (font.widthOfTextAtSize(s, size) <= maxW) return s;
  let lo = 1;
  let hi = s.length;
  let best = "";
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    const sub = s.slice(0, mid);
    if (font.widthOfTextAtSize(sub, size) <= maxW) {
      best = sub;
      lo = mid + 1;
    } else {
      hi = mid - 1;
    }
  }
  return best || s.slice(0, 1);
}

function wrapLine(font: { widthOfTextAtSize: (t: string, s: number) => number }, text: string, size: number, maxW: number): string[] {
  const t = text.trim() || " ";
  const words = t.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = "";
  for (const w of words) {
    const test = cur ? `${cur} ${w}` : w;
    if (font.widthOfTextAtSize(test, size) <= maxW) {
      cur = test;
    } else {
      if (cur) lines.push(cur);
      cur = "";
      let rest = w;
      while (rest.length > 0) {
        const chunk = longestFittingPrefix(font, rest, size, maxW);
        lines.push(chunk);
        rest = rest.slice(chunk.length);
      }
    }
  }
  if (cur) lines.push(cur);
  return lines.length ? lines : [" "];
}

type DrawCtx = {
  pdf: PDFDocument;
  page: PDFPage;
  y: number;
  font: PDFFont;
  fontBold: PDFFont;
};

const PAGE_BOTTOM = MARGIN + FOOTER_RESERVE;

async function ensureSpace(ctx: DrawCtx, need: number): Promise<void> {
  if (ctx.y - need < PAGE_BOTTOM) {
    ctx.page = ctx.pdf.addPage([PAGE_W, PAGE_H]);
    ctx.y = PAGE_H - MARGIN;
  }
}

async function drawParagraph(ctx: DrawCtx, text: string, size: number, bold = false, muted = false): Promise<void> {
  const maxW = PAGE_W - 2 * MARGIN;
  const font = bold ? ctx.fontBold : ctx.font;
  const lines = wrapLine(font, text, size, maxW);
  const color = muted ? rgb(0.38, 0.38, 0.42) : rgb(0.1, 0.1, 0.12);
  for (const line of lines) {
    await ensureSpace(ctx, LINE);
    ctx.page.drawText(line, {
      x: MARGIN,
      y: ctx.y,
      size,
      font,
      color,
    });
    ctx.y -= LINE;
  }
}

function strProp(row: Record<string, unknown>, snake: string, camel?: string): string {
  const v = (row[snake] ?? (camel ? row[camel] : undefined)) as string | undefined;
  return (v ?? "").trim();
}

function numProp(row: Record<string, unknown>, key: string): number {
  const v = row[key];
  if (typeof v === "number" && !Number.isNaN(v)) return v;
  return 0;
}

function tagsProp(row: Record<string, unknown>): string[] {
  const raw = row["pdf_issue_tag_names"];
  if (!Array.isArray(raw)) return [];
  return raw.filter((x): x is string => typeof x === "string" && x.length > 0);
}

function formatHumanDate(iso?: string | null): string {
  if (!iso) return "—";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
  });
}

function propertyAddressLines(property: Record<string, unknown>): string[] {
  const line1 = strProp(property, "address_line_1", "address_line1");
  const line2 = strProp(property, "address_line_2", "address_line2");
  const city = strProp(property, "city");
  const region = strProp(property, "province_state");
  const postal = strProp(property, "postal_code");
  const cityLine = [city, region].filter(Boolean).join(", ");
  return [line1, line2, cityLine, postal].filter(Boolean);
}

function addFootersToAllPages(pdf: PDFDocument, font: PDFFont, generatedLabel: string): void {
  const pages = pdf.getPages();
  const total = pages.length;
  const muted = rgb(0.45, 0.45, 0.48);

  for (let i = 0; i < pages.length; i++) {
    const page = pages[i];
    page.drawText(`Generated by MoveMark · ${generatedLabel}`, {
      x: MARGIN,
      y: 34,
      size: 8,
      font,
      color: muted,
    });
    page.drawText(`Page ${i + 1} of ${total}`, {
      x: PAGE_W - MARGIN - 52,
      y: 34,
      size: 8,
      font,
      color: muted,
    });
    page.drawText("MoveMark organizes user-submitted proof and does not provide legal advice.", {
      x: MARGIN,
      y: 20,
      size: 7,
      font,
      color: muted,
    });
  }
}

async function embedPhotoImage(pdf: PDFDocument, bytes: Uint8Array): Promise<PDFImage | null> {
  try {
    if (bytes.length >= 2 && bytes[0] === 0xff && bytes[1] === 0xd8) {
      return await pdf.embedJpg(bytes);
    }
    return await pdf.embedPng(bytes);
  } catch {
    return null;
  }
}

async function drawCoverPage(
  ctx: DrawCtx,
  reportTitle: string,
  property: Record<string, unknown>,
  generatedAt: string
): Promise<void> {
  const title = strProp(property, "title") || "Untitled property";
  const addressBits = propertyAddressLines(property);

  ctx.y = PAGE_H - MARGIN - 20;
  await drawParagraph(ctx, "MoveMark", TITLE, true);
  ctx.y -= 4;
  await drawParagraph(ctx, reportTitle, SUBTITLE, true);
  ctx.y -= 18;

  await drawParagraph(ctx, title, HEAD, true);
  for (const bit of addressBits) {
    await drawParagraph(ctx, bit, BODY);
  }
  if (addressBits.length === 0) {
    await drawParagraph(ctx, "Address not on file.", BODY, false, true);
  }

  ctx.y -= 10;
  await drawParagraph(ctx, `Generated ${formatHumanDate(generatedAt)}`, META, false, true);
  ctx.y -= 16;
  await drawParagraph(
    ctx,
    "This report organizes renter-submitted move-in proof. It is not legal advice.",
    BODY,
    false,
    true
  );
}

async function drawChecklistRow(ctx: DrawCtx, label: string, done: boolean, detail?: string): Promise<void> {
  const mark = done ? "[x]" : "[ ]";
  await drawParagraph(ctx, `${mark} ${label}`, BODY, true);
  if (detail) {
    await drawParagraph(ctx, detail, META, false, true);
  }
}

type RoomPhotoGroup = {
  roomId: string;
  roomName: string;
  photos: PdfEvidencePhotoInput[];
  itemCount: number;
};

function buildRoomPhotoGroups(
  rooms: Array<Record<string, unknown>>,
  inspectionItems: Array<Record<string, unknown>>,
  evidencePhotos: PdfEvidencePhotoInput[]
): { groups: RoomPhotoGroup[]; missingRoomNames: string[] } {
  const roomNameById = new Map<string, string>();
  for (const r of rooms) {
    const id = r["id"] as string | undefined;
    if (id) roomNameById.set(id, ((r["name"] as string) ?? id).trim() || id);
  }

  const itemsByRoom = new Map<string, number>();
  for (const item of inspectionItems) {
    const rid = (item["room_id"] as string | undefined) ?? "";
    if (!rid) continue;
    itemsByRoom.set(rid, (itemsByRoom.get(rid) ?? 0) + 1);
  }

  const photosByRoom = new Map<string, PdfEvidencePhotoInput[]>();
  for (const photo of evidencePhotos) {
    const rid = photo.roomId ?? "";
    const list = photosByRoom.get(rid) ?? [];
    list.push(photo);
    photosByRoom.set(rid, list);
  }

  const groups: RoomPhotoGroup[] = [];
  const documentedRoomIds = new Set<string>();

  for (const r of rooms) {
    const id = r["id"] as string | undefined;
    if (!id) continue;
    const photos = photosByRoom.get(id) ?? [];
    const itemCount = itemsByRoom.get(id) ?? 0;
    if (photos.length > 0 || itemCount > 0) {
      documentedRoomIds.add(id);
      groups.push({
        roomId: id,
        roomName: roomNameById.get(id) ?? "Room",
        photos,
        itemCount,
      });
    }
  }

  for (const [rid, photos] of photosByRoom) {
    if (!rid || documentedRoomIds.has(rid)) continue;
    groups.push({
      roomId: rid,
      roomName: roomNameById.get(rid) ?? "Unassigned room",
      photos,
      itemCount: itemsByRoom.get(rid) ?? 0,
    });
  }

  const missingRoomNames = rooms
    .map((r) => {
      const id = r["id"] as string | undefined;
      if (!id || documentedRoomIds.has(id)) return null;
      return roomNameById.get(id) ?? "Room";
    })
    .filter((n): n is string => Boolean(n));

  return { groups, missingRoomNames };
}

async function drawPhotoCell(
  ctx: DrawCtx,
  photo: PdfEvidencePhotoInput,
  x: number,
  cellW: number
): Promise<number> {
  const imgTop = ctx.y;
  const imgH = PHOTO_CELL_H - PHOTO_CAPTION_H;
  let drawnH = imgH;

  if (photo.imageBytes) {
    const embedded = await embedPhotoImage(ctx.pdf, photo.imageBytes);
    if (embedded) {
      const scale = Math.min(cellW / embedded.width, imgH / embedded.height);
      const w = embedded.width * scale;
      const h = embedded.height * scale;
      const offsetX = x + (cellW - w) / 2;
      const offsetY = imgTop - h;
      ctx.page.drawImage(embedded, { x: offsetX, y: offsetY, width: w, height: h });
      drawnH = h;
    } else {
      ctx.page.drawRectangle({
        x,
        y: imgTop - imgH,
        width: cellW,
        height: imgH,
        borderColor: rgb(0.75, 0.75, 0.78),
        borderWidth: 0.5,
      });
      ctx.page.drawText("Photo unavailable", {
        x: x + 8,
        y: imgTop - imgH / 2,
        size: META,
        font: ctx.font,
        color: rgb(0.45, 0.45, 0.48),
      });
    }
  } else {
    ctx.page.drawRectangle({
      x,
      y: imgTop - imgH,
      width: cellW,
      height: imgH,
      borderColor: rgb(0.75, 0.75, 0.78),
      borderWidth: 0.5,
    });
    ctx.page.drawText("Photo unavailable", {
      x: x + 8,
      y: imgTop - imgH / 2,
      size: META,
      font: ctx.font,
      color: rgb(0.45, 0.45, 0.48),
    });
  }

  const captionY = imgTop - drawnH - 8;
  const timestamp = formatHumanDate(photo.capturedAt ?? photo.createdAt);
  ctx.page.drawText(timestamp, { x, y: captionY, size: META, font: ctx.font, color: rgb(0.35, 0.35, 0.38) });

  let capY = captionY - 10;
  if (photo.tags.length > 0) {
    const tagLine = `Tags: ${photo.tags.join(", ")}`;
    const lines = wrapLine(ctx.font, tagLine, META, cellW);
    for (const line of lines.slice(0, 2)) {
      ctx.page.drawText(line, { x, y: capY, size: META, font: ctx.font, color: rgb(0.35, 0.35, 0.38) });
      capY -= 9;
    }
  }

  const notes = photo.notes?.trim();
  if (notes) {
    const lines = wrapLine(ctx.font, notes.replace(/\n/g, " "), META, cellW);
    for (const line of lines.slice(0, 2)) {
      ctx.page.drawText(line, { x, y: capY, size: META, font: ctx.font, color: rgb(0.35, 0.35, 0.38) });
      capY -= 9;
    }
  }

  return PHOTO_CELL_H;
}

async function drawPhotoGrid(ctx: DrawCtx, photos: PdfEvidencePhotoInput[]): Promise<void> {
  if (photos.length === 0) {
    await drawParagraph(ctx, "No photos added for this room.", BODY, false, true);
    return;
  }

  const cellW = (PAGE_W - 2 * MARGIN - PHOTO_GAP * (PHOTO_COLS - 1)) / PHOTO_COLS;

  for (let i = 0; i < photos.length; i += PHOTO_COLS) {
    await ensureSpace(ctx, PHOTO_CELL_H + 8);
    const rowPhotos = photos.slice(i, i + PHOTO_COLS);
    const rowStartY = ctx.y;

    for (let col = 0; col < rowPhotos.length; col++) {
      const x = MARGIN + col * (cellW + PHOTO_GAP);
      ctx.y = rowStartY;
      await drawPhotoCell(ctx, rowPhotos[col], x, cellW);
    }

    ctx.y = rowStartY - PHOTO_CELL_H - 8;
  }
}

export async function generateMoveInPdfBuffer(input: {
  property: Record<string, unknown>;
  rooms: Array<Record<string, unknown>>;
  inspection: Record<string, unknown> | null;
  inspectionItems: Array<Record<string, unknown>>;
  propertyDocuments: Array<Record<string, unknown>>;
  evidencePhotos?: PdfEvidencePhotoInput[];
}): Promise<Buffer> {
  const generatedAt = new Date().toISOString();
  const evidencePhotos = input.evidencePhotos ?? [];

  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  let page = pdf.addPage([PAGE_W, PAGE_H]);
  const ctx: DrawCtx = { pdf, page, y: PAGE_H - MARGIN, font, fontBold };

  await drawCoverPage(ctx, "Move-in Proof Report", input.property, generatedAt);

  ctx.page = pdf.addPage([PAGE_W, PAGE_H]);
  ctx.y = PAGE_H - MARGIN;
  await drawParagraph(ctx, "Property summary", HEAD, true);
  ctx.y -= 6;

  const title = strProp(input.property, "title") || "Untitled";
  await drawParagraph(ctx, `Rental: ${title}`, BODY, true);
  const addressBits = propertyAddressLines(input.property);
  if (addressBits.length > 0) {
    await drawParagraph(ctx, `Location: ${addressBits.join(", ")}`, BODY);
  }
  await drawParagraph(ctx, "Phase: Move-in", BODY);
  ctx.y -= 6;

  const totalPhotos = evidencePhotos.length > 0
    ? evidencePhotos.length
    : input.inspectionItems.reduce((sum, item) => sum + numProp(item, "pdf_photo_count"), 0);

  const totalTags = input.inspectionItems.reduce((sum, item) => sum + tagsProp(item).length, 0);
  const { groups, missingRoomNames } = buildRoomPhotoGroups(input.rooms, input.inspectionItems, evidencePhotos);
  const documentedRooms = groups.filter((g) => g.photos.length > 0 || g.itemCount > 0).length;

  await drawParagraph(ctx, `Rooms documented: ${documentedRooms} of ${input.rooms.length}`, BODY);
  await drawParagraph(ctx, `Photos on file: ${totalPhotos}`, BODY);
  await drawParagraph(ctx, `Tagged issues: ${totalTags}`, BODY);
  await drawParagraph(ctx, `Supporting documents: ${input.propertyDocuments.length}`, BODY);

  ctx.page = pdf.addPage([PAGE_W, PAGE_H]);
  ctx.y = PAGE_H - MARGIN;
  await drawParagraph(ctx, "Proof summary", HEAD, true);
  ctx.y -= 8;

  const hasRoomPhotos = totalPhotos > 0;
  const hasLeaseDocs = input.propertyDocuments.length >= 1;
  await drawChecklistRow(ctx, "Room photos", hasRoomPhotos, hasRoomPhotos ? `${totalPhotos} photo(s) included` : "No room photos yet");
  await drawChecklistRow(
    ctx,
    "Lease / docs",
    hasLeaseDocs,
    hasLeaseDocs ? `${input.propertyDocuments.length} document(s) on file` : "No supporting documents attached"
  );
  await drawChecklistRow(ctx, "Damage tags", totalTags > 0, totalTags > 0 ? `${totalTags} tag(s) recorded` : "No damage tags recorded");
  await drawChecklistRow(ctx, "Report generated", true, formatHumanDate(generatedAt));

  if (missingRoomNames.length > 0) {
    ctx.y -= 10;
    await drawParagraph(ctx, "Rooms without proof", HEAD, true);
    for (const name of missingRoomNames) {
      await drawParagraph(ctx, `• ${name} — no photos or inspection items`, BODY, false, true);
    }
  }

  ctx.page = pdf.addPage([PAGE_W, PAGE_H]);
  ctx.y = PAGE_H - MARGIN;
  await drawParagraph(ctx, "Room-by-room evidence", HEAD, true);
  ctx.y -= 8;

  if (groups.length === 0) {
    await drawParagraph(ctx, "No move-in room proof recorded.", BODY);
  } else {
    for (const group of groups) {
      await ensureSpace(ctx, 60);
      await drawParagraph(ctx, group.roomName, HEAD, true);
      ctx.y -= 4;
      await drawPhotoGrid(ctx, group.photos);
      ctx.y -= 10;
    }
  }

  ctx.y -= 6;
  await ensureSpace(ctx, 80);
  await drawParagraph(ctx, "Supporting documents", HEAD, true);
  if (input.propertyDocuments.length === 0) {
    await drawParagraph(ctx, "No supporting documents attached.", BODY, false, true);
  } else {
    for (const d of input.propertyDocuments) {
      await ensureSpace(ctx, LINE + 4);
      const dt = (d["document_type"] as string | undefined) ?? "document";
      const fn = (d["file_name"] as string | undefined) ?? "";
      const uploaded = formatHumanDate((d["uploaded_at"] as string | undefined) ?? null);
      await drawParagraph(ctx, `• ${dt}${fn ? ` — ${fn}` : ""}${uploaded !== "—" ? ` (${uploaded})` : ""}`, BODY);
    }
  }

  addFootersToAllPages(pdf, font, formatHumanDate(generatedAt));

  const bytes = await pdf.save();
  return Buffer.from(bytes);
}

export async function generateMoveOutPdfBuffer(input: {
  property: Record<string, unknown>;
  rooms: Array<Record<string, unknown>>;
  inspection: Record<string, unknown> | null;
  inspectionItems: Array<Record<string, unknown>>;
  evidencePhotos?: PdfEvidencePhotoInput[];
}): Promise<Buffer> {
  const generatedAt = new Date().toISOString();
  const evidencePhotos = input.evidencePhotos ?? [];

  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  let page = pdf.addPage([PAGE_W, PAGE_H]);
  const ctx: DrawCtx = { pdf, page, y: PAGE_H - MARGIN, font, fontBold };

  await drawCoverPage(ctx, "Move-out Proof Report", input.property, generatedAt);

  ctx.page = pdf.addPage([PAGE_W, PAGE_H]);
  ctx.y = PAGE_H - MARGIN;

  const totalPhotos = evidencePhotos.length > 0
    ? evidencePhotos.length
    : input.inspectionItems.reduce((sum, item) => sum + numProp(item, "pdf_photo_count"), 0);

  await drawParagraph(ctx, "Property summary", HEAD, true);
  ctx.y -= 6;
  await drawParagraph(ctx, `Rental: ${strProp(input.property, "title") || "Untitled"}`, BODY, true);
  await drawParagraph(ctx, "Phase: Move-out", BODY);
  await drawParagraph(ctx, `Rooms: ${input.rooms.length} · Photos: ${totalPhotos}`, BODY);
  ctx.y -= 10;

  const { groups, missingRoomNames } = buildRoomPhotoGroups(input.rooms, input.inspectionItems, evidencePhotos);

  await drawParagraph(ctx, "Room-by-room evidence", HEAD, true);
  if (groups.length === 0) {
    await drawParagraph(ctx, "No move-out room proof recorded.", BODY);
  } else {
    for (const group of groups) {
      await ensureSpace(ctx, 60);
      await drawParagraph(ctx, group.roomName, HEAD, true);
      ctx.y -= 4;
      await drawPhotoGrid(ctx, group.photos);
      ctx.y -= 10;
    }
  }

  if (missingRoomNames.length > 0) {
    ctx.y -= 6;
    await drawParagraph(ctx, "Rooms without move-out proof", HEAD, true);
    for (const name of missingRoomNames) {
      await drawParagraph(ctx, `• ${name}`, BODY, false, true);
    }
  }

  addFootersToAllPages(pdf, font, formatHumanDate(generatedAt));

  const bytes = await pdf.save();
  return Buffer.from(bytes);
}

export type DisputePacketChecklist = {
  moveInReport: string;
  moveOutReport: string;
  leaseAndDepositDocs: string[];
  damageNotes: string[];
  timeline: string[];
};

export async function generateDisputePacketPdfBuffer(input: {
  property: Record<string, unknown>;
  checklist: DisputePacketChecklist;
}): Promise<Buffer> {
  const generatedAt = new Date().toISOString();
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  let page = pdf.addPage([PAGE_W, PAGE_H]);
  const ctx: DrawCtx = { pdf, page, y: PAGE_H - MARGIN, font, fontBold };

  await drawCoverPage(ctx, "Dispute Evidence Packet", input.property, generatedAt);

  ctx.page = pdf.addPage([PAGE_W, PAGE_H]);
  ctx.y = PAGE_H - MARGIN;

  await drawParagraph(ctx, "Proof checklist", HEAD, true);
  ctx.y -= 4;
  await drawParagraph(ctx, `Move-in report: ${input.checklist.moveInReport}`, BODY);
  await drawParagraph(ctx, `Move-out report: ${input.checklist.moveOutReport}`, BODY);
  ctx.y -= 8;

  await drawParagraph(ctx, "Lease / deposit documents", HEAD, true);
  if (input.checklist.leaseAndDepositDocs.length === 0) {
    await drawParagraph(ctx, "No supporting documents attached.", BODY, false, true);
  } else {
    for (const doc of input.checklist.leaseAndDepositDocs) {
      await drawParagraph(ctx, `• ${doc}`, BODY);
    }
  }
  ctx.y -= 8;

  await drawParagraph(ctx, "Damage notes", HEAD, true);
  if (input.checklist.damageNotes.length === 0) {
    await drawParagraph(ctx, "No tagged damage notes on file.", BODY, false, true);
  } else {
    for (const note of input.checklist.damageNotes) {
      await drawParagraph(ctx, `• ${note}`, BODY);
    }
  }
  ctx.y -= 8;

  await drawParagraph(ctx, "Timeline summary", HEAD, true);
  if (input.checklist.timeline.length === 0) {
    await drawParagraph(ctx, "No dated events on file.", BODY, false, true);
  } else {
    for (const line of input.checklist.timeline) {
      await drawParagraph(ctx, `• ${line}`, BODY);
    }
  }

  addFootersToAllPages(pdf, font, formatHumanDate(generatedAt));

  const bytes = await pdf.save();
  return Buffer.from(bytes);
}
